#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N dot
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Send mail at submission and completion of script
#$ -m be
# Request a gpu

#$ -q datasci

/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load CUDA module
. /opt/modules/init/bash
module load cuda

#module load gsl-gnu4
#export LD_LIBRARY_PATH=/opt/gsl/1.15/gnu4/lib:$LD_LIBRARY_PATH

#Full path to executable
#Replace usman's home directory path with yours in the command below

#/usr/bin/time -f %e -o chi2time_ /home/s/sap254/assignment1/assignment1 4 3 0 256 /home/s/sap254/assignment1/data.txt /home/s/sap254/assignment1/vector.txt > output_
/usr/bin/time -f %e -o chi2time /afs/cad/courses/ccs/s19/cs/677/002/sap254/assignment1/assignment1 4 3 0 256 /afs/cad/courses/ccs/s19/cs/677/002/sap254/assignment1/data.txt /afs/cad/courses/ccs/s19/cs/677/002/sap254/assignment1/vector.txt > output_

#/usr/bin/time -f %e -o chi2time /home/u/usman/courses/cs698_spring18/Chi2/Chi2_serial /home/u/usman/courses/cs698_spring18/Chi2/traindata 8000 29623 4000 4000 > output_serial
#/usr/bin/time -f %e -o chi2time_serial /home/u/usman/courses/cs698_spring18/Chi2/Chi2_serial /home/u/usman/courses/cs698_spring18/data_fixed_.01 4901 422006 1963 2938 > output_serial

